<!--<div class="container">
    <div class="hero-unit">
    <h1>Welcome to the Network</h1>
    <p>
        The ultimate community site, where beginners to seasoned players can 
        interact with one another and talk about their passion.
    </p>
    <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="span4">
            <h2>Events</h2>
            <p>Full listings of all the events in the UK, with the option to buy direct from us, securely and in confidence. We also offer players the chance to setup their own events and offer tickets for free.</p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>Community Features</h2>
            <p>We have the largest range of community features for players:</p>
            <ul>
                <li>Forums</li>
                <li>Groups</li>
                <li>Profile pages</li>
                <li>Group and P chat</li>
                <li>Weekly Competitions</li>
            </ul>
            <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>We've got the Magazine</h2>
            <p>We're working in partnership with <a href="#">Paintball Scene magazine</a>, the monthly paintball magazine, to bring it direct to you, the players in a format that you can read anywhere.</p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="span4">
            <h2>Guides and Reviews</h2>
            <p>Each week we'll bring you the latest product reviews and monthly guides to get you at the top of your game. With dedicated sections for </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>Community Features</h2>
            <p>We have the largest range of community features for players:</p>
            <ul>
                <li>Forums</li>
                <li>Groups</li>
                <li>Profile pages</li>
                <li>Group and P chat</li>
                <li>Weekly Competitions</li>
            </ul>
            <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>We've got the Magazine</h2>
            <p>We're working in partnership with <a href="#">Paintball Scene magazine</a>, the monthly paintball magazine, to bring it direct to you, the players in a format that you can read anywhere.</p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
    </div>
</div>-->
<div class="container">
    <div class="hero-unit home">
        <h1>The ultimate paintball website</h1>
        <h2>News, Community and Events</h2>
    </div>
    <div class="home block span4">
        <h2>We'll be launching soon</h2>
        <p>Until then, you can sign up for updates and early access.</p>
        <form class="form-inline" action="/index/index" method="POST">
        <fieldset>
            <div class="control-group">
                <div class="controls">
                <div class="input-append">
                    <input class="span3" id="appendedPrependedInput" name="email" size="16" placeholder="enter your email address" type="text"><button class="btn btn-inverse" type="submit">Subscribe</button>
                </div>
                </div>
            </div>
        </fieldset>
      </form>
    </div>
</div>