<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit visible-desktop visible-tablet hidden-phone">
    <h1>Rise of the student cup <small>Featured article</small></h1>
    <p>
        From what started out as a conversation in a field, in what was later dubbed the student village at the anual North vs South game. The student cup quickly begin to take shape.
    </p>
    <p>
        The ultimate community site, where beginners to seasoned players can 
        interact with one another and talk about their passion.
    </p>
    <p><a class="btn btn-primary btn-large">Read more &raquo;</a></p>
</div>
<div class="page-header">
    <h1>Latest News</h1>
</div>
<div class="clearfix" style="margin-top:20px;">
    <div class="span10" style="margin-left:0;">
        <ul style="list-style:none; margin-left:0;">
            <? 
            foreach($this->articles as $article)
            {
                $profile = $article->getAuthor()->getProfile();
            ?>
            <li>
                <div class="span1 visible-desktop visible-tablet hidden-phone" style="margin-left:0;">
                    <a href="#" class="thumbnail"><img src="<?=$article->getAuthor()->getProfile()->getPicture()?>" /></a>
                </div>
                <div class="span9" style="margin-left:20px;">
                    <h2><?=$article->getTitle()?> <small style="font-size:14px;"><?=$article->getPosted("l, jS F Y")?></small></h2>
                    <p>
                        <strong><?=$article->getSummary()?></strong>
                        <br /> <span><i>posted by</i> <a href="#"><?=ucwords($profile->getFirstName()." ".$profile->getLastName())?></a></span>
                    </p>
                    <hr />
                    <?=$article->getContent()?>
                    <hr />
                    <div>
                        <i class="icon-tags"></i>
                        <span><a href="" class="label label-info">Community</a></span>
                        <span><a href="" class="label label-important">Announcement</a></span>
                        <a href="#" class="btn btn-small btn-inverse pull-right">Read More &raquo;</a>
                    </div>
                </div>
            </li>
           <? } ?>
        </ul>
    </div>
    <div class="span2 visible-desktop visible-tablet hidden-phone">
        <h3>Advert</h3>
    </div>
</div>