<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit visible-desktop visible-tablet hidden-phone">
    <h1>Rise of the student cup <small>Featured article</small></h1>
    <p>
        From what started out as a conversation in a field, in what was later dubbed the student village at the anual North vs South game. The student cup quickly begin to take shape.
    </p>
    <p>
        The ultimate community site, where beginners to seasoned players can 
        interact with one another and talk about their passion.
    </p>
    <p><a class="btn btn-primary btn-large">Read more &raquo;</a></p>
</div>

<h1>Latest News</h1>

<div class="clearfix" style="margin-top:20px;">
    <div class="span10" style="margin-left:0;">
        <ul style="list-style:none; margin-left:0;">
            <li>
                <div class="span1 visible-desktop visible-tablet hidden-phone" style="margin-left:0;">
                    <a href="#" class="thumbnail"><img src="/img/profiles/default.jpg" /></a>
                </div>
                <div class="span9" style="margin-left:20px;">
                    <h2>News article 1 <small style="font-size:14px;">Monday, 23rd March 2012</small></h2>
                    <p>
                        <strong>An introduction to the article, a teaser of what to come.</strong>
                        <br /> <a href="#">Jason Brown</a>
                    </p>
                    <hr />
                    <p>Fylde College had the highest number of voters, with 420 voting in the contest of President, which resulted in ex-Fylde President and current LUSU Campaigns Cross Campus Officer, Ste Smith, being elected LUSU President.</p>
                    <p>In terms of the number of votes cast, the second highest college was County, who elected three of their own students. Libby Martin, Liz Ashworth and Rachel Harvey were elected LUSU Vice Presidents (Events and Democracy), (Activities), and (Media and Communications) respectively.
                    </p>
                    <p>Fylde College had the highest number of voters, with 420 voting in the contest of President, which resulted in ex-Fylde President and current LUSU Campaigns Cross Campus Officer, Ste Smith, being elected LUSU President.</p>
                    <hr />
                    <div>
                        <a href="#" class="btn btn-small btn-inverse pull-right">Read More &raquo;</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="span1 visible-desktop visible-tablet hidden-phone" style="margin-left:0;">
                    <a href="#" class="thumbnail"><img src="/img/profiles/default.jpg" /></a>
                </div>
                <div class="span9" style="margin-left:20px;">
                    <h2>News article 1 <small style="font-size:14px;">Monday, 23rd March 2012</small></h2>
                    <p>
                        <strong>An introduction to the article, a teaser of what to come.</strong>
                        <br /> <a href="#">Jason Brown</a>
                    </p>
                    <hr />
                    <p>Fylde College had the highest number of voters, with 420 voting in the contest of President, which resulted in ex-Fylde President and current LUSU Campaigns Cross Campus Officer, Ste Smith, being elected LUSU President.</p>
                    <p>In terms of the number of votes cast, the second highest college was County, who elected three of their own students. Libby Martin, Liz Ashworth and Rachel Harvey were elected LUSU Vice Presidents (Events and Democracy), (Activities), and (Media and Communications) respectively.
                    </p>
                    <p>Fylde College had the highest number of voters, with 420 voting in the contest of President, which resulted in ex-Fylde President and current LUSU Campaigns Cross Campus Officer, Ste Smith, being elected LUSU President.</p>
                    <hr />
                    <div>
                        <a href="#" class="btn btn-small btn-inverse pull-right">Read More &raquo;</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="span1 visible-desktop visible-tablet hidden-phone" style="margin-left:0;">
                    <a href="#" class="thumbnail"><img src="/img/profiles/default.jpg" /></a>
                </div>
                <div class="span9" style="margin-left:20px;">
                    <h2>News article 1 <small style="font-size:14px;">Monday, 23rd March 2012</small></h2>
                    <p>
                        <strong>An introduction to the article, a teaser of what to come.</strong>
                        <br /> <a href="#">Jason Brown</a>
                    </p>
                    <hr />
                    <p>Fylde College had the highest number of voters, with 420 voting in the contest of President, which resulted in ex-Fylde President and current LUSU Campaigns Cross Campus Officer, Ste Smith, being elected LUSU President.</p>
                    <p>In terms of the number of votes cast, the second highest college was County, who elected three of their own students. Libby Martin, Liz Ashworth and Rachel Harvey were elected LUSU Vice Presidents (Events and Democracy), (Activities), and (Media and Communications) respectively.
                    </p>
                    <p>Fylde College had the highest number of voters, with 420 voting in the contest of President, which resulted in ex-Fylde President and current LUSU Campaigns Cross Campus Officer, Ste Smith, being elected LUSU President.</p>
                    <hr />
                    <div>
                        <a href="#" class="btn btn-small btn-inverse pull-right">Read More &raquo;</a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="span2 visible-desktop visible-tablet hidden-phone">
        <h3>Advert</h3>
    </div>
</div>