<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit visible-desktop visible-tablet hidden-phone block" style="display:none;">
    <h1>Rise of the student cup <small>Featured article</small></h1>
    <p>
        From what started out as a conversation in a field, in what was later dubbed the student village at the anual North vs South game. The student cup quickly begin to take shape.
    </p>
    <p>
        The ultimate community site, where beginners to seasoned players can 
        interact with one another and talk about their passion.
    </p>
    <p><a class="btn btn-inverse btn-large">Read more &raquo;</a></p>
</div>
<div class="page-header">
    <h1>Latest News</h1>
</div>

<div class="row">
    <div class="span8">
        <ul class="articles">
            <? 
            foreach($this->articles as $article)
            {
                $profile = $article->getAuthor()->getProfile();
            ?>
            <li class="article">
                <div class="row">
                    <div class="span8">
                        <h2><a href="<?=$this->baseUrl('/news/index/view/id/'.$article->getId())?>"><?=$article->getTitle()?></a>
                            <br/><small style="font-size:14px;"><?=$article->getPosted("l, jS F Y")?></small>
                            <span><a href="" class="label label-info">Community</a></span>
                            <span><a href="" class="label label-important">Announcement</a></span>
                        </h2>
                        <p><strong><?=$article->getSummary()?></strong></p>
                        <span class="posted"><a href="#"><?=ucwords($profile->getFullName())?></a><?=($article->hasBeenEdited() ? ", updated on <strong>".$article->getUpdated("l, jS F Y")."</strong>" : "")?></span>
                        <div class="content">
                            <?=$article->getContent()?>
                        </div>
                        <div>
                            <!--<a href="#" class="btn btn-small btn-inverse pull-right">Read More &raquo;</a>-->
                        </div>
                    </div>
                </div>
            </li>
        <? } ?>
        </ul>
    </div>
    <div class="span4">
        <div class="advert">
            <h3>Advert</h3>
        </div>
    </div>
</div>

