<div class="row">
    <div class="articles">
        <div class="article">
            <div class="span8">
                <h2><a href="<?=$this->baseUrl('/news/index/view/id/'.$this->article->getId())?>"><?=$this->article->getTitle()?></a>
                    <br/><small style="font-size:14px;"><?=$this->article->getPosted("l, jS F Y")?></small>
                    <span><a href="" class="label label-info">Community</a></span>
                    <span><a href="" class="label label-important">Announcement</a></span>
                </h2>
                <p><strong><?=$this->article->getSummary()?></strong></p>
                <span class="posted"><a href="#"><?=ucwords($this->article->getAuthor()->getProfile()->getFullName())?></a><?=($this->article->hasBeenEdited() ? ", updated on <strong>".$this->article->getUpdated("l, jS F Y")."</strong>" : "")?></span>
                <div class="content">
                    <?=$this->article->getContent()?>
                </div>
                <div>
                    <!--<a href="#" class="btn btn-small btn-inverse pull-right">Read More &raquo;</a>-->
                </div>
            </div>
        </div>
        <div class="span4 visible-desktop visible-tablet hidden-phone">
            <?=$this->partial('partials/recentByAuthor.phtml',array('articles' => $this->recentByAuthor))?>
            <?=$this->partial('partials/recentArticles.phtml',array('articles' => $this->recentArticles))?>
        </div>
        <div class="clearfix"></div>
    </div>
</div>