<div class="container-fluid articles">
    <div class="span8" style="margin-left:0;">
        <div class="page-header">
            <div class="span1 visible-desktop visible-tablet hidden-phone" style="margin-left:0;">
                <a href="<?=$this->baseUrl('/profile/view/id/'.$this->article->getAuthor()->getId())?>" class="thumbnail"><img src="<?=$this->article->getAuthor()->getProfile()->getPicture()?>" /></a>
            </div>
            <div class="span7">
                <h1><?=$this->article->getTitle()?> <small style="font-size:14px;"><?=($this->article->isPublished())? $this->article->getPosted("l, jS F Y") : ""?></small></h1>
                <p>
                    <strong><?=$this->article->getSummary()?></strong>
                    <br /><span>Posted by <a href="<?=$this->baseUrl('/profile/view/id/'.$this->article->getAuthor()->getId())?>"><?=$this->article->getAuthor()->getProfile()->getFullName()?></a><?=($this->article->hasBeenEdited() ? ", updated on <strong>".$this->article->getUpdated("l, jS F Y")."</strong></span>" : "")?>
                </p>
                <div>
                    <i class="icon-tags"></i>
                    <span><a href="" class="label label-info">Community</a></span>
                    <span><a href="" class="label label-important">Announcement</a></span>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <?=$this->article->getContent()?>
        <hr />
    </div>

    <div class="span3 visible-desktop visible-tablet hidden-phone">
        <?=$this->partial('partials/recentByAuthor.phtml',array('articles' => $this->recentByAuthor))?>
        <?=$this->partial('partials/recentArticles.phtml',array('articles' => $this->recentArticles))?>
    </div>
    <div class="clearfix"></div>
</div>