<style>
    .input {margin-bottom:10px !important;}
</style>
<div class="row-fluid">
    <div class="span12">
        <div style="background:white; padding:20px 20px 20px 20px; margin-left:0;">
            <div class="page-header">
                <h1>Lets create your profile</h1>
            </div>
            <form method="<?=$this->form->getMethod()?>" action="<?=$this->form->getAction()?>" class="form-inline">
            <div class="pull-left">
                <div class="thumbnail span2" style="margin-left:0 !important;">
                    <img src="/img/profiles/default.jpg" />
                </div>
                <div class="span3">
                    <h3>Personal Details</h3>
                    
                    <?php
                    echo $this->form->getElement('first');
                    echo $this->form->getElement('last');
                    echo $this->form->getElement('dob');
                    ?>

                    <div class="control-group">
                        <div class="controls">
                        <div class="input-prepend input-append">
                            <span class="add-on location-tip" rel='tooltip' title="Use your current location"><i class='icon-map-marker'></i></span><input class="input-medium location" data-provide="typeahead" placeholder="your location" id="appendedPrependedInput" size="16" type="text"><span class="add-on question" rel="popover" data-content="We use your location to provide better results when searching for events, friends and venues." data-original-title="Using your location"><i class="icon-question-sign"></i></span>
                        </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
            <div class="pull-left">
                <div class="span3" style="margin-left:0 !important;">
                    <h3>Additional Info</h3>
                    <?php
                    echo $this->form->getElement('interests');
                    ?>
                    <ul id="interests-holder">
                        <!-- Displays interests -->
                    </ul>
                </div>
            </div>
            </form>
            <div>
                <div>
                    <h3>Be Social <small>it's easy</small></h3>
                </div>
            </div>
            
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.location-tip').tooltip({
           'placement' : 'top'
        });
        
        // Start type ahead
        $('.location').typeahead(
        {
            'source' : ['<?=  implode("','", \Zend_Registry::get('locations'))?>']
        });
        
        // Start pop over
        $('.question').popover();
        
        // Load interests
        $("#interests").keyup(function()
        {
            // Check for enter key
            var value = $(this).attr('value');

            $.getJSON('/profile/interests', {"interest" : value}, function(data, status)
            {
                // Display interest in box
                $("#interests-holder").append("<li><i class='icon-tag'></i> "+data+"</li>");
                
            });
        });
        
    });
    
    // Allow browser to locate our user
    /*if (navigator.geolocation) 
    {
        navigator.geolocation.getCurrentPosition( 

            function (position) {  

                // Did we get the position correctly?
                // alert (position.coords.latitude);

                // To see everything available in the position.coords array:
                // for (key in position.coords) {alert(key)}

                mapServiceProvider(position.coords.latitude,position.coords.longitude);

            }, 
            // next function is the error callback
            function (error)
            {
                    switch(error.code) 
                    {
                            case error.TIMEOUT:
                                    alert ('Timeout');
                                    break;
                            case error.POSITION_UNAVAILABLE:
                                    alert ('Position unavailable');
                                    break;
                            case error.PERMISSION_DENIED:
                                    alert ('Permission denied');
                                    break;
                            case error.UNKNOWN_ERROR:
                                    alert ('Unknown error');
                                    break;
                    }
            }
        );
    }
    
    function mapServiceProvider(latitude,longitude)
    {
        mapThisGoogle(latitude,longitude);
    }
    
    function mapThisGoogle(latitude,longitude)
    {
            geocoder = new google.maps.Geocoder();
            var latlng = new google.maps.LatLng(latitude,longitude);
        
            
        geocoder.geocode({'latLng': latlng}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[1]) {
                   
                    alert(results[1].address_components);
                    $.each(results[1].address_components, function (i, address_component) {
                    if (address_component.types[0] == "locality") // locality type
                        alert(address_component.long_name); // here's your town name
                        return false; // break the loop
                    });
                } else {
                    alert("No results found");
                }
            } else {
                alert("Geocoder failed due to: " + status);
            }
        });
    }*/

    
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>