<?php
    $profile = $this->user->getProfile();
?>
<div id="profile-header" class="well well-large">
    <div class="span2">
        <div class="thumbnail">
            <img src="<?=$profile->getPicture()?>" />
        </div>
        <div id="level-box">
            <h5>Current level: <small>Level 5</small></h5>
            <div rel="tooltip" title="Your 588xp away from reaching Level 6" class="progress progress-warning xp">
                <div class="bar" style="width: 60%;">1320xp</div>
            </div>
        </div>
    </div>
    <div class="span9">
        <div class="page-header">
            <h2><?=ucwords($profile->getFirstName()." ".$profile->getLastName())?> <small><?=$this->user->getUsername()?></small></h2>
            <p class="status-message span9"><?=$profile->getBio()?></p>
        </div>
        <!-- Profile head boxes -->
        <ul id="profile-boxes">
            <li class="span2 first">
                
            </li>
            <li class="span2">
                
            </li>
            <li class="span2">
                
            </li>
        </ul>
    </div>
    <div class="clearfix"></div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.xp').tooltip({
           'placement' : 'top'
        });
    });
</script>