<table class="table table-striped">
  <thead>
    <tr style="text-transform: uppercase;">
      <th>id</th>
      <th>username</th>
      <th>email address</th>
      <th>created</th>
      <th>status</th>
      <th>access level</th>
      <th>actions</th>
    </tr>
  </thead>
  <tbody>
    <?php
    foreach($this->users as $user)
    {
    ?>
    <tr>
        <td><?=$user->getId();?></td>
        <td><?=$user->getUsername();?></td>
        <td><?=$user->getEmailAddress();?></td>
        <td><?=$user->getCreated('H:ia, D dS M Y');?></td>
        <td><?=($user->isActive() == 1 ? 'active' : 'inactive');?></td>
        <td><?=$user->getRoleId();?></td>
        <td>
            <div class="btn-group">
                <a href="<?=$this->url(array(
                        'module' => 'admin',
                        'controller' => 'user',
                        'action' => 'edit',
                        'id' => $user->getId()
                        ))?>" class="btn">Edit
                </a>
                <button class="btn dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right">
                    <li class="delete"><a rel="<?=$this->url(array(
                        'module' => 'admin',
                        'controller' => 'user',
                        'action' => 'delete',
                        'id' => $user->getId()
                        ))?>">Delete</a></li>
                    <li class=""><a href="">Block</a></li>
                    <li class="divider"></li>
                    <li class="access"><a rel="<?=$user->getId();?>" class="<?=$user->getRoleId();?>">Change Access</a></li>
                </ul>
            </div>
        </td>
    </tr>
    <?
    }
    ?>
  </tbody>
</table>

<!-- Delete modal -->
<div class="modal fade" id="delete">
  <div class="modal-header">
    <h3>Delete User</h3>
  </div>
  <div class="modal-body">
    <p>This action is irreversible, are you sure you want to delete this user?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    <a href="#" class="btn btn-danger">Delete User</a>
  </div>
</div>

<!-- Permissions modal -->
<div class="modal fade" id="access">
  <div class="modal-header">
    <h3>Change User access permissions</h3>
  </div>
  <div class="modal-body">
    <div class="alert alert-info">
        <p>Modifying a user's access permissions will change the level of site functionality they have access to, be <strong>careful</strong>, you don't want to grant a user more access than they should have.</p>
    </div>
      <?php echo $this->permissionForm;?>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function()
    {
        $(".delete a").click(function()
        {
            $("#delete .modal-footer .btn-danger").attr('href', $(this).attr('rel'));
            $('#delete').modal('toggle');
        });
        
        $(".access a").click(function()
        {
            $("#access #permissions").attr('action', '/admin/user/permissions/id/'+$(this).attr('rel'));
            $("#access #permissions #_roleId").val($(this).attr('class'));
            $('#access').modal('toggle');
        });
        
    });
</script>
