<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?php echo $this->baseUrl('/'); ?>">the Paintball Network</a>
            <div class="nav-collapse">
                <?php 
                $partial = array('partials/menu.phtml', 'site');
                $this->navigation()->menu()->setPartial($partial);
                echo $this->navigation()->menu()->render(); ?>
                <ul class="nav pull-right">
                    <li class="divider-vertical"></li>
                    <li><a href="<?php echo $this->baseUrl('/');?>">Back to site</a></li>
                    <li class="divider-vertical"></li>
                    <?php echo $this->loggedInAs(); ?>
                </ul>
            </div>
        </div>
    </div>
</div>