<link rel="stylesheet" type="text/css" href="/css/calendar.css" />
<div id="calendarWrapper">
    <div id="calendarHeader">
        <a href="<?php echo $this->url($this->previousMonth); ?>">Previous</a>
        <h2><?php echo $this->monthHeader; ?></h2>
        <a href="<?php echo $this->url($this->nextMonth); ?>">Next</a>
    </div>
    <div id="calendarBody">
        <table id="calendarTable" border="0" cellpadding="0" cellspacing="0">
            <tr class="weekdays">
                <?php foreach ($this->calWeekdays as $arr) : ?>
                <td class="<?php echo $arr['class']; ?>"><?php echo $arr['dayShortStr']; ?></td>
                <?php endforeach; ?>
            </tr>
            <?php foreach ($this->calMonthDays as $weekNum => $weekArr) : ?>
            <tr class="days">
                <?php foreach ($weekArr as $dayArr) : ?>
                <td class="<?php echo $dayArr['class']; ?>">
                    <?php if (isset($dayArr['num'])) : ?>
                    <span class="dayNum"><?php echo $dayArr['num']; ?></span>
                    <?php endif; ?>
                </td>
                <?php endforeach; ?>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>