<div class="block" style="text-align:center;">
    <h1>Account Activation</h1>
    <p>Thanks for signing up, we just need to activate your account first.</p>
    <form class="form-inline">
        <div class="control-group">
            <div class="controls">
                <div class="input-append">
                    <input id="appendedPrependedInput" name="code" size="16" placeholder="enter the code we emailed you" type="text"><button class="btn btn-inverse" type="submit">Activate</button>
                </div>
                <?
                if($this->error != null){
                ?>
                <p style="margin:10px 0 0 0; padding:0; color:red;"><?=$this->error?></p>        
                <?
                }?>
            </div>
        </div>
    </form>
</div>