<div style="background:white; padding:20px 20px 0 20px; margin-left:0;" class="span4">
    <div class="page-header">
        <h1>Login <small>or login with </small><a href="/auth/login/facebook/true"><img src="/img/fb-login.png" alt="fb-login"/></a></h1>
    </div>
    <?=$this->form?>
</div>
<div style="background:white; padding:20px 20px 0 20px" class="span7">
    <div class="page-header">
        <h1>Register <small>or connect with </small><a href="/auth/register/facebook/true"><img src="/img/fb-login.png" alt="fb-login"/></a></h1>
    </div>
     <?=$this->register?>
</div>
