<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120210175312 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE cart ADD customer_id VARCHAR(255) NOT NULL, ADD transaction_id VARCHAR(255) NOT NULL, ADD session_id VARCHAR(255) NOT NULL, ADD complete TINYINT(1) NOT NULL, ADD completed_on DATETIME NOT NULL, ADD payment_method VARCHAR(255) NOT NULL, ADD subtotal NUMERIC(10, 0) NOT NULL, ADD total NUMERIC(10, 0) NOT NULL, ADD status VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE cart DROP customer_id, DROP transaction_id, DROP session_id, DROP complete, DROP completed_on, DROP payment_method, DROP subtotal, DROP total, DROP status");
    }
}
