<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120209165313 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Ticket (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, price DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE event ADD free TINYINT(1) NOT NULL, ADD price DOUBLE PRECISION NOT NULL, CHANGE location location VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(500) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Ticket");
        $this->addSql("ALTER TABLE event DROP free, DROP price, CHANGE location location VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(500) NOT NULL");
    }
}
