<div class="container">
    <!-- Main hero unit for a primary marketing message or call to action -->
    <div class="hero-unit">
    <h1>Community</h1>
    <p>
        The ultimate community site, where beginners to seasoned players can 
        interact with one another and talk about their passion.
    </p>
    </div>
    <ul class="breadcrumb">
        <li>Forums</li>
        <li class="divider">/</li>
        <li><a href="">Banter</a></li>
    </ul>
    <div class="row">
        <div class="span4">
            <h2>Recent Forum Activity</h2>
            <p>Catch up with friends, keep up to date with the latest goings on within the community.</p>
            <p><a class="btn" href="#">Visit Forums &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>Weekly Competitions</h2>
            <p>Each week we run competitions</p>
            <ul>
                <li>Forums</li>
                <li>Groups</li>
                <li>Profile pages</li>
                <li>Group and P chat</li>
                <li>Weekly Competitions</li>
            </ul>
            <p><a class="btn" href="#">Sign up &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>Newsletter</h2>
            <p>Receive email updates and notifications</p>
        </div>
    </div>
</div>