<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit well">
    <h1>Community</h1>
<p>Welcome to the community portal, where you'll find out what's going on throughout the entire paintball community</p>
</div>
<div class="row">
    <div class="span3 well">
        <h2>Forum Activity</h2>
        <?=$this->partial('partials/forumActivity.phtml', array('posts' => $this->recentPosts))?>
        <p><a class="btn" href="#">Visit Forums &raquo;</a></p>
    </div>
    <div class="span4 well">
        <h2>Newsletter</h2>
        <p>Receive email updates and notifications</p>
        <form class="form-inline" action="/" method="POST">
            <fieldset>
                <div class="control-group">
                    <div class="controls">
                        <div class="input-append">
                            <input class="span3" id="appendedPrependedInput" name="email" size="16" placeholder="enter your email address" type="text"><button class="btn btn-inverse" type="submit">Subscribe</button>
                        </div>
                        <?
                        if($this->error != null){
                        ?>
                        <p style="margin:10px 0 0 0; padding:0; color:red;"><?=$this->error?></p>        
                        <?
                        }?>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>