<div class="container">
    <div class="hero-unit">
        <h1>Forums</h1>
        <p>
            The ultimate community site, where beginners to seasoned players can 
            interact with one another and talk about their passion.
        </p>
    </div>
    <ul class="breadcrumb" id="top">
        <li>Forums</li>
        <li class="divider">/</li>
        <li><a href="">Banter</a></li>
    </ul>
    <table class="table table-striped table-bordered" id="<?=str_replace(" ", "",$this->thread->getName())?>">
        <thead style="margin-bottom:10px;">
            <tr>
                <h3 class="pull-left"><span rel="tooltip" title="<?=$this->thread->getDescription()?>"class="headertip"><?=ucwords($this->thread->getName())?></span></h3>
                <a href="<?=$this->url(array(
                    'module' => 'community',
                    'controller' => 'post',
                    'action' => 'add',
                    'thread' => $this->thread->getId()
                ))?>" class="btn btn-primary btn-mini pull-right"><i class="icon-pencil icon-white"></i> New Post</a>
            </tr>
        </thead>
        <tbody>
        <?
        foreach($this->thread->getPosts() as $post)
        {
            ?>
            <tr>
                <td>
                    <div class="profile-block">
                        <?=$post->getUser()->getUsername()?>
                    </div>
                    <div class="post">
                        <?=$post->getContent()?>
                    </div>
                </td>
            </tr>
            <?
        }
        ?>
            <tr>
                <td>
                    <?=$this->postForm?>
                </td>
            </tr>
        </tbody>
    </table>
    <ul class="breadcrumb">
        <li>Forums</li>
        <li class="divider">/</li>
        <li><a href="">Banter</a></li>
    </ul>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('a').tooltip({
           'placement' : 'top'
        });
    });
</script>