<div class="container">
    <div class="hero-unit">
        <h1>Forums</h1>
        <p>
            The ultimate community site, where beginners to seasoned players can 
            interact with one another and talk about their passion.
        </p>
    </div>
    <ul class="breadcrumb" id="top">
        <li>Forums</li>
        <li class="divider">/</li>
        <li><a href="">Banter</a></li>
    </ul>
    <table class="table table-striped table-bordered" id="<?=str_replace(" ", "",$this->thread->getName())?>">
        <thead style="margin-bottom:10px;">
            <tr>
                <h3 class="pull-left"><span rel="tooltip" title="<?=$this->thread->getDescription()?>"class="headertip"><?=ucwords($this->thread->getName())?></span></h3>
                <a href="<?=$this->url(array(
                    'module' => 'community',
                    'controller' => 'post',
                    'action' => 'add',
                    'thread' => $this->thread->getId()
                ))?>" class="btn btn-primary btn-mini pull-right"><i class="icon-pencil icon-white"></i> New Post</a>
            </tr>
        </thead>
        <tbody>
        <?
        foreach($this->thread->getPosts() as $key => $post)
        {
            ?>
            <tr>
                <td class="span12 post">
                    <div class="profile-block pull-left">
                        <div class="avatar">
                            <a href="<?=$this->url(array(
                                'module' => 'site',
                                'controller' => 'profile',
                                'action' => 'view',
                                'id' => $post->getUser()->getId()
                            ))?>" class="thumbnail"><img src="<?=$post->getUser()->getProfile()->getPicture()?>" /></a>
                        </div>
                        <h4><?=ucwords($post->getUser()->getUsername())?></h4>
                        <p>Posts: <?=$post->getUser()->getPostCount()?></p>
                    </div>
                    <div class="pull-left">
                        <div class="post-mast">
                            <span><strong>#<?=($key+1)?></strong> Posted: <i><?=$post->getCreated("g:ia l jS F Y")?></i></span>
                        </div>
                        <div class="post-content">
                            <?=$post->getContent()?>
                        </div>
                    </div>
                    <span class="pull-right"><a href="#" title="Reply to this post" rel="tooltip"><i class="icon-share-alt"></i> Reply</a></span>
                </td>
            </tr>
            <?
        }
        ?>
            <tr>
                <td>
                    
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td>
                    <a href="<?=$this->url(array(
                            'module' => 'community',
                            'controller' => 'post',
                            'action' => 'add',
                            'thread' => $this->thread->getId()
                        ))?>" class="btn btn-primary btn-mini pull-right"><i class="icon-pencil icon-white"></i> New Post</a>
                </td>
            </tr>
        </tfoot>
    </table>
    <ul class="breadcrumb">
        <li>Forums</li>
        <li class="divider">/</li>
        <li><a href="">Banter</a></li>
    </ul>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('a').tooltip({
           'placement' : 'top'
        });
    });
</script>