<div class="container">
    <div class="hero-unit visible-desktop visible-tablet block">
        <h1>Forums</h1>
        <p>
            Where beginners to seasoned players can 
            interact with one another and talk about their passion.
        </p>
    </div>
    <?php
    foreach($this->categories as $category)
    {
        ?>
        <table class="table table-striped table-bordered" id="<?=str_replace(" ", "",$category->getName())?>">
            <thead>
                <tr><h3><span rel="tooltip" title="<?=$category->getDescription()?>"class="headertip"><?=ucwords($category->getName())?></span></h3></tr>
            </thead>
            <tbody>
            <?
            foreach($category->getForums() as $forum)
            {
                ?>
                <tr>
                    <td class="span7">
                        <h4><a href="<?=$this->url(array(
                            'module' => 'forum',
                            'controller' => 'thread',
                            'action' => 'view',
                            'id' => $forum->getId()
                            ))?>"><i class="<? echo ($forum->open ? 'icon-folder-open' : 'icon-folder-close');?>"></i> <?=ucwords($forum->getName())?></a> <small class="visible-desktop visible-tablet"><?=$forum->getDescription()?></small>
                        </h4>
                    </td>
                    <td class="span1">
                        <? $threads = $forum->getThreadCount(); ?>
                        <a href="#" rel="tooltip" title="Thread Count: <?=$threads?>"><i class="icon-th-list"></i> <?=$threads?></a>
                    </td>
                    <td class="span1">
                        <? 
                        $posts = 0;
                        foreach($forum->getThreads() as $thread){ 
                            $posts += $thread->getPostCount();
                        }
                        ?>
                        <a href="#" rel="tooltip" title="Post Count: <?=$posts?>"><i class="icon-comment"></i> <?=$posts?></a>
                    </td>
                    <td class="span3">
                        <?php
                        if(!is_null($forum->latestPost))
                        {
                            ?>
                            <p><a href="/forum/post/index/thread/<?=$forum->latestPost->getThread()->getId()?>/id/<?=$forum->getId()?>"><?=ucwords($forum->latestPost->getThread()->getName())?></a>
                            by 
                            <?
                            echo "<strong>".ucwords($forum->latestPost->getUser()->getUsername())."</strong> ";
                            if($forum->latestPost->getCreated('d-m-Y') == date('d-m-Y'))
                            {
                                echo "Today at ".$forum->latestPost->getCreated('H:ia');
                            }else{
                                echo "on ".$forum->latestPost->getCreated('jS M \'y');
                            }
                            ?></p><?
                        }
                        ?>
                    </td>
                </tr>
                <?
            }
            ?>
            </tbody>
        </table>
        <?
    }
    ?>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.headertip').tooltip({
           'placement' : 'right'
        });
        
        $('.span1 a').tooltip({
           'placement' : 'top'
        });
        
    });
</script>