<!-- Recent news articles by author -->
<? if(count($this->articles>0)){ ?>
<div class="span3 well block">
    <h3>Articles by <?=$this->articles[0]->getAuthor()->getProfile()->getFullName()?></h3>
    <ul>
    <? 
    foreach($this->articles as $article)
    {
        ?>
        <li>
            <h4><a href="<?=$this->baseUrl('/news/index/view/id/'.$article->getId())?>"><?=ucwords($article->getTitle())?></a> <small><?=($article->isPublished())? $article->getPosted("l, jS F Y") : ""?></small></h4>
        </li>
        <?
    }
    ?>
    </ul>
</div>
<? } ?>