<div class="container">
    <div class="hero-unit visible-desktop visible-tablet">
        <h1>Forums</h1>
        <p>
            The ultimate community site, where beginners to seasoned players can 
            interact with one another and talk about their passion.
        </p>
    </div>
    <?php
    foreach($this->categories as $category)
    {
        ?>
        <table class="table table-striped table-bordered" id="<?=str_replace(" ", "",$category->getName())?>">
            <thead>
                <tr><h3><span rel="tooltip" title="<?=$category->getDescription()?>"class="headertip"><?=ucwords($category->getName())?></span></h3></tr>
            </thead>
            <tbody>
            <?
            foreach($category->getForums() as $forum)
            {
                ?>
                <tr>
                    <td class="span10">
                        <h4><a href="<?=$this->url(array(
                            'module' => 'community',
                            'controller' => 'thread',
                            'action' => 'view',
                            'id' => $forum->getId()
                            ))?>"><i class="<? echo ($forum->open ? 'icon-folder-open' : 'icon-folder-close');?>"></i> <?=ucwords($forum->getName())?></a> <small class="visible-desktop visible-tablet"><?=$forum->getDescription()?></small>
                        </h4>
                    </td>
                    <td class="span2"></td>
                </tr>
                <?
            }
            ?>
            </tbody>
        </table>
        <?
    }
    ?>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.headertip').tooltip({
           'placement' : 'right'
        });
    });
</script>