<div class="container">
    <div class="hero-unit visible-desktop visible-tablet">
        <h1>Forums</h1>
        <p>
            The ultimate community site, where beginners to seasoned players can 
            interact with one another and talk about their passion.
        </p>
    </div>
    <ul class="breadcrumb" id="top">
        <li>Forums</li>
        <li class="divider">/</li>
        <li><a href="">Banter</a></li>
    </ul>
    <table class="table table-striped table-bordered" id="<?=str_replace(" ", "",$this->forum->getName())?>">
        <thead style="margin-bottom:10px;">
            <tr>
                <h3 class="pull-left"><span rel="tooltip" title="<?=$this->forum->getDescription()?>"class="headertip"><?=ucwords($this->forum->getName())?></span></h3>
            </tr>
            <tr><a href="<?=$this->url(array(
                    'module' => 'community',
                    'controller' => 'thread',
                    'action' => 'add',
                    'forum' => $this->forum->getId()
                ))?>" class="btn btn-primary btn-mini pull-right"><i class="icon-comment icon-white"></i> New Thread</a></tr>
        </thead>
        <tbody>
        <?
        foreach($this->forum->getThreads() as $thread)
        {
            ?>
            <tr>
                <td class="span8">
                    <h4 class="pull-left">
                        <a href="<?=$this->url(array(
                            'module' => 'community',
                            'controller' => 'post',
                            'action' => 'index',
                            'thread' => $thread->getId()
                        ))?>"><i class="<? echo ($thread->locked ? 'icon-folder-close' : 'icon-folder-open');?>"></i> <?=ucwords($thread->getName())?></a> <small class="visible-desktop visible-tablet"><?=$thread->getDescription()?></small>
                    </h4>
                </td>
                <td class="span1">
                   
                </td>
                <td class="span1">
                    
                </td>
                <td class="span2">
                    <i class="icon-comment" title="Updated: <?=$thread->getUpdated('dS F \'y , H:iA')?>"></i> <strong><?=$thread->getPostCount()?> posts</strong>
                </td>
            </tr>
            <?
        }
        ?>
        </tbody>
    </table>
    <ul class="breadcrumb">
        <li>Forums</li>
        <li class="divider">/</li>
        <li><a href="">Banter</a></li>
    </ul>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.headertip').tooltip({
           'placement' : 'right'
        });
        
        $('i.icon-comment').tooltip({
           'placement' : 'left'
        });
    });
</script>