<h3>Forums</h3>
<div class="pull-right">
    <a href="<?=$this->url(array(
        'module' => 'admin',
        'controller' => 'forum',
        'action' => 'create'
    ))?>" class="btn btn-primary">New Forum</a>
</div>
<table class="table table-striped">
  <thead>
    <tr style="text-transform: uppercase;">
      <th>id</th>
      <th>name</th>
      <th>description</th>
      <th>thread count</th>
      <th>post count</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php
    foreach($this->forums as $forum)
    {
    ?>
    <tr>
        <td><?=$forum->getId();?></td>
        <td><?=$forum->getName();?></td>
        <td><?=$forum->getDescription();?></td>
        <td><?=$forum->getThreadCount();?></td>
        <td></td>
        <td>
            <div class="btn-group pull-right">
                <a href="<?=$this->url(array(
                        'module' => 'admin',
                        'controller' => 'forum',
                        'action' => 'edit',
                        'id' => $forum->getId()
                        ))?>" class="btn">Edit
                </a>
                <button class="btn dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right">
                    <li class="delete"><a rel="<?=$this->url(array(
                        'module' => 'admin',
                        'controller' => 'forum',
                        'action' => 'delete',
                        'id' => $forum->getId()
                        ))?>">Delete</a></li>
                    <li class=""><a href="">Lock</a></li>
                    <li class="access"><a rel="<?=$forum->getId();?>">Change Access</a></li>
                    <li class="divider"></li>
                    <li><a href="<?=$this->url(array(
                        'module' => 'community',
                        'controller' => 'thread',
                        'action' => 'view',
                        'id' => $forum->getId()
                        ));?>">View Forum</a></li>
                </ul>
            </div>
        </td>
    </tr>
    <?
    }
    ?>
  </tbody>
</table>

<!-- Delete modal -->
<div class="modal fade" id="delete">
  <div class="modal-header">
    <h3>Delete User</h3>
  </div>
  <div class="modal-body">
    <p>This action is irreversible, are you sure you want to delete this user?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    <a href="#" class="btn btn-danger">Delete User</a>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function()
    {
        $(".delete a").click(function()
        {
            $("#delete .modal-footer .btn-danger").attr('href', $(this).attr('rel'));
            $('#delete').modal('toggle');
        });
        
        $(".access a").click(function()
        {
            $("#access #permissions").attr('action', '/admin/user/permissions/id/'+$(this).attr('rel'));
            $("#access #permissions #_roleId").val($(this).attr('class'));
            $('#access').modal('toggle');
        });
        
    });
</script>